# -*- coding: utf-8 -*-
"""aula_lista.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1olaimIj_28ji0FaWGPE0k1RBiymvdwAV

# Vetores (array)

O exemplo a seguir já fora visto por todos nós anteriormente.
"""

n = 5
soma = 0
print(f'Digite os {n} numeros:')

for i in range(n):
    numero = int(input())
    soma += numero
media = soma / n
print(f'Media: {media}.')

"""É possível definir variáveis que guardam **mais de um valor** de um mesmo tipo.

Essas variáveis são conhecidas como **arranjo (array) ou vetor**.

O **vetor** possui um **identificador** e cada elemento que o compõe pode
ser **individualizado/referenciado por meio de um índice**.

Vamos utilizar uma variável composta do tipo lista ***(list)***.

Em Python os elementos de uma lista podem ser de qualquer tipo,
porém em muitas linguagens os elementos precisam ser do mesmo tipo.

"""

# Inicializando um vetor com valores predefinidos

nomes = ['João', 'Maria', 'Pedro']
print(nomes)
print(nomes[0])
print(nomes[1])
print(nomes[2])

# Inicializando um vetor com valores nulos

vetor = [None] * 5
print(vetor)

"""Para acessarmos todos os elementos de um vetor, podemos utilizar o
comando ***for***.
"""

# Exemplo: Lendo 3 nomes e armazenando em um vetor

n = 3
v = [None] * n

for i in range(n):
    v[i] = input()
print(v)

# Exemplo: Exibindo os elementos de um vetor, sendo um por linha.

nomes = ['João', 'Maria', 'Pedro']

for i in range(3):
    print(nomes[i])

# Utilizando o próprio vetor como objeto iterável do for:

nomes = ['João', 'Maria', 'Pedro']

for e in nomes:
    print(e)

"""**Cuidados** ao manipular vetores:
   

* Acessar uma posição inválida de um vetor causará um erro na
execução do programa.





"""

nomes = ['João', 'Maria', 'Pedro']
print(nomes[3])  # Isso resultará em um erro

"""**Cuidados** ao manipular vetores:
* Um vetor não pode ser atribuído diretamente para outro vetor.

"""

# Ex: Suponha que eu queira copiar os elementos de um vetor a para
# um vetor b.

a = [1, 2, 3]
b = a
print('a =', a)
print('b =', b)

a[1] = 0
print()
print('a =', a)
# Note que a e b tornaram-se o mesmo vetor, apenas com nomes diferentes.
print('b =', b)
# Na prática, b é um espelho de a.

"""Vamos ver agora a **solução** do problema anterior."""

# Solução para resolver o problema anterior (copiar os elementos de um
# vetor para outro):

n = 3
a = [1, 2, 3]
b = [None] * n

for i in range(n):
    b[i] = a[i]
print('a =', a)
print('b =', b)

a[1] = 0
print()
print('a =', a)
print('b =', b)

"""Resolvendo o problema do cenário inicial."""

# Ler N números inteiros, calcular e exibir a média dos números lidos e
# mostrar quais os números acima dessa média.

n = 5
vetor = [None] * 5
soma = 0
print(f'Digite os {n} numeros:')

for i in range(n):
    vetor[i] = int(input())
    soma += vetor[i]
media = soma / n
print(f'Media: {media}.')
print('Os números acima da média são:')

for e in vetor:
    if e > media:
        print(e)
